scala

mushroomDF.printSchema()

root
 |-- class: string (nullable = true)
 |-- capshape: string (nullable = true)
 |-- capsurface: string (nullable = true)
 |-- capcolor: string (nullable = true)
 |-- bruises: string (nullable = true)
 |-- odor: string (nullable = true)
 |-- gillattachment: string (nullable = true)
 |-- gillspacing: string (nullable = true)
 |-- gillsize: string (nullable = true)
 |-- gillcolor: string (nullable = true)
 |-- stalkshape: string (nullable = true)
 |-- stalkroot: string (nullable = true)
 |-- stalksurfaceabovering: string (nullable = true)
 |-- stalksurfacebelowring: string (nullable = true)
 |-- stalkcolorabovering: string (nullable = true)
 |-- stalkcolorbelowring: string (nullable = true)
 |-- veiltype: string (nullable = true)
 |-- veilcolor: string (nullable = true)
 |-- ringnumber: string (nullable = true)
 |-- ringtype: string (nullable = true)
 |-- sporeprintcolor: string (nullable = true)
 |-- population: string (nullable = true)
 |-- habitat: string (nullable = true)
 |-- class_indexed: double (nullable = false)
 |-- capshape_indexed: double (nullable = false)
 |-- capsurface_indexed: double (nullable = false)
 |-- capcolor_indexed: double (nullable = false)
 |-- bruises_indexed: double (nullable = false)
 |-- odor_indexed: double (nullable = false)
 |-- gillattachment_indexed: double (nullable = false)
 |-- gillspacing_indexed: double (nullable = false)
 |-- gillsize_indexed: double (nullable = false)
 |-- gillcolor_indexed: double (nullable = false)
 |-- stalkshape_indexed: double (nullable = false)
 |-- stalkroot_indexed: double (nullable = false)
 |-- stalksurfaceabovering_indexed: double (nullable = false)
 |-- stalksurfacebelowring_indexed: double (nullable = false)
 |-- stalkcolorabovering_indexed: double (nullable = false)
 |-- stalkcolorbelowring_indexed: double (nullable = false)
 |-- veiltype_indexed: double (nullable = false)
 |-- veilcolor_indexed: double (nullable = false)
 |-- ringnumber_indexed: double (nullable = false)
 |-- ringtype_indexed: double (nullable = false)
 |-- sporeprintcolor_indexed: double (nullable = false)
 |-- population_indexed: double (nullable = false)
 |-- habitat_indexed: double (nullable = false)
